## NumPy
- NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrics, along with a collection of mathematical functions to operate on these data structures. 
- Focused Topic : Basic NumPy, Arrays, Vectorized Operations.

In [ ]:
#Install numpy in Jupyter Notebook
!pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   -----------------

In [3]:
import numpy as np

##### 1. Creating Array using NumPy

a) Creating 1D Array

In [4]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [7]:
print(type(arr1))   # ndarray = n dimention array

print(arr1.shape)   # 1D / 2D ? (n,) = 1D;  (m,n) = 2D

<class 'numpy.ndarray'>
(5,)


b) Converting 1D array to 2D Array

In [10]:
arr2 = np.array([1,2,3,4,5])   #1D

arr2 = arr2.reshape(1,5)     #2D   | 1 row, 5 col
print(arr2)

[[1 2 3 4 5]]


c) Creating 2D Array

In [12]:
arr2 = np.array([[1,2,3,4,5],
                 [6,7,8,9,2]])
print(arr2)
print(arr2.shape)   # r=2, c=5

[[1 2 3 4 5]
 [6 7 8 9 2]]
(2, 5)


d) Create Array with Inbuilt Function

In [10]:
# arange(from, to-1, step)  
# reshape(row, col)

np.arange(0,10,2).reshape(5,1)  

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
np.ones((3,4))  ## all are 1 with 3 rows, 4 cols

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
## Creating Identity Matrix

np.eye(5)    # means : (5x5) matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
# Attributes of NumPy

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape) # Output: (2, 3)
print("Number of dimensions:", arr.ndim) # Output: 2
print("Size (number of elements):", arr.size) # Output: 6
print("Data type:", arr.dtype) # Output: int64 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize) # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


e) NumPy Vectorized Operation

In [15]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [17]:
## Universal Function

arr = np.array([2,3,4,5,6])

## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [21]:
## array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)


Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [36]:
# Accessing Element (Index)
print(arr[0][0])    # arr[row][col]

# Slicing  ( Wanna Print : 7,8,11,12)

print(arr[1:])  # All from row 1

print(arr[1:, 2:]) # All from row 1 and col 2   :: Output


1
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 7  8]
 [11 12]]


In [37]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

# print : 3,4,7,8

print("One :\n" ,arr[0:, 2:])  # row 0 to all, col 2 to all

print("Two :\n" ,arr[0:2])    # row 0 to row 1 (from : to-1)

print("Final :\n" ,arr[0:2, 2:])

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
One :
 [[ 3  4]
 [ 7  8]
 [11 12]]
Two :
 [[1 2 3 4]
 [5 6 7 8]]
Final :
 [[3 4]
 [7 8]]


In [45]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

# Print : 6,7,10,11

# Step 1
print("Step 1 (Choose Rows):\n", arr[1:])

# Choose with colums
print("Final Output : \n", arr[1:, 1:3])

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Step 1 (Choose Rows):
 [[ 5  6  7  8]
 [ 9 10 11 12]]
Final Output : 
 [[ 6  7]
 [10 11]]


In [46]:
# Modify Array Elements
print("Existing :\n", arr)

# Modify
arr[0,0] = 100

print("Updated :\n", arr)

Existing :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Updated :
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [47]:
arr[1:] = 100      # All elements from row 1 will change
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


### Practical Examples

In [49]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [51]:
## Statistical concepts -- Normalization
## To have a mean of 0 and standard deviation of 1

data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)


Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [57]:
## Logical Operation

info = np.array([1,2,3,4,5,6,7,8,9,10])

print(info>5)   # Logical outputs

print(info[info>5])   # Values

print(info[(info>=5) & (info<=8)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[5 6 7 8]
